### ISSUE TITLE
Enable GitHub Actions for code coverage

### ISSUE THREAD

**Issue by BALaka-18** [Open-Dev-Community/URL-Shortener#2]
## Enable GitHub Actions for code coverage.

Integrate the most appropriate GitHub Action for automatic generation of code coverage report on every code related PR made.

## Instructions

- Once assigned, please comment here as to which GitHub Action you're going to integrate before creating a PR. I will approve the Action, only then you may integrate it.

Please add/delete options that are not relevant.

- [ ] Improving Code

### Programming Language

- [ ] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by mdb571** [comment]
are you looking for [codecov](https://github.com/codecov/codecov-action)?

**Comment by BALaka-18** [comment]
> are you looking for [codecov](https://github.com/codecov/codecov-action)?

Yup exactly. Shall I assign it to you ?

**Comment by mdb571** [comment]
> > are you looking for [codecov](https://github.com/codecov/codecov-action)?
> 
> Yup exactly. Shall I assign it to you ?

sure

**Comment by bucharitesh** [comment]
can you assign it to me  ?
